version: '3'
services:
  interactive-rating:
    container_name: interactive-rating
    build: .
    ports:
      - '5000:5000'
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
volumes:
  node_modules: {}
